CREATE TABLE IF NOT EXISTS budgets (
  user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  monthly_limit INTEGER NOT NULL DEFAULT 50000,
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
